### ISSUE TITLE
No device is detected

### ISSUE THREAD

**Issue by elax46** [shaiu/technicolor#11]
I followed what is described but no device is detected by the integration even when entering the data
![Immagine 2022-02-12 161033](https://user-images.githubusercontent.com/55278049/153716796-f6e057b5-cb15-4409-a775-11fee6f94dda.png)

**Comment by nimroddolev** [comment]
I have the same issue

**Comment by shaiu** [comment]
@nimroddolev @elax46 
Do you see anything in the logs? some errors?

**Comment by elax46** [comment]
> @nimroddolev @elax46 Do you see anything in the logs? some errors?

no kind of error

**Comment by shaiu** [comment]
@elax46

can you please add this to your configuration.yaml:

```
logger:
  default: warning
  logs:
    custom_components.technicolor: debug
```
1. then remove the custom component
2. restart HA
3. add the component again

Look at the logs and please attach relevant logs here (mask your ips if there are)

**Comment by elax46** [comment]
> @elax46
> 
> can you please add this to your configuration.yaml:
> 
> ```
> logger:
>   default: warning
>   logs:
>     custom_components.technicolor: debug
> ```
> 
> 1. then remove the custom component
> 2. restart HA
> 3. add the component again
> 
> Look at the logs and please attach relevant logs here (mask your ips if there are)

here's how you requested!

`2022-02-15 21:11:45 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration technicolor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

`Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/logging/handlers.py", line 1518, in _monitor
self.handle(record)
File "/usr/local/lib/python3.9/logging/handlers.py", line 1499, in handle
handler.handle(record)
File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
self.emit(record)
File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 192, in emit
entry = LogEntry(record, stack, _figure_out_source(record, stack, self.hass))
File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 99, in __init__
self.message = deque([record.getMessage()], maxlen=5)
File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
2022-02-15 21:13:54 INFO (MainThread) [custom_components.technicolor.device_tracker] add_entities tracked $set()`

**Comment by shaiu** [comment]
@elax46 
Are there more logs with "custom_components.technicolor"?

**Comment by elax46** [comment]
> @elax46 Are there more logs with "custom_components.technicolor"?

no

**Comment by potasoa** [comment]
I have the same problem. The log shows the message:
2022-03-04 22:22:31 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration technicolor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by potasoa** [comment]
How can I check that connection with router is opened?

**Comment by shaiu** [comment]
@elax46 @potasoa 

I need your help.
I need the html page of your device-modal from your router.
You can find it at: http://192.168.1.1/modals/device-modal.lp (could be that your router has a different ip address)
Please note that this holds all your ip/mac addresses of your router. This is sensitive data. I understand if you don't want to share it so you can just change the numbers to what ever you want. Because all I need is the structure of the page (could be that it's different than mine)
Also what is your router model? You can find that information at: http://192.168.1.1/modals/gateway-modal.lp

Thanks

**Comment by potasoa** [comment]
Hope this screenshot is useful. Thanks!!!
[image: imagen.png]

**Comment by shaiu** [comment]
@potasoa I don't think you uploaded the image

**Comment by potasoa** [comment]
Sorry, I can see it in my mail program. I attach here
![imagen00](https://user-images.githubusercontent.com/59341672/158075722-97c4d309-1d88-4de4-b0f7-dbaa71febdb8.png)
.

**Comment by shaiu** [comment]
@potasoa Are you sure you have a technicolor modem?

Anyway this screenshot doesn't help me.

@nimroddolev @elax46 it will be very helpful if you can give me what I asked for above.
Without more info I can't solve the issue.

**Comment by potasoa** [comment]
Sorry Shaiu, my english is not good ennough. I guess that is a technicolor modem beccause it has been detected by Home Assitant as PnP device:
![image](https://user-images.githubusercontent.com/59341672/158178647-3f6d28b8-7d3b-4895-8c5e-4c3551550588.png)
Regarding to the device-modal, the link provided is in error. Please, giveme  the information needed to look for it in router configuration. The model es Technicolor CGA4233, as you can see in the screenshot
Many thanks

**Comment by shaiu** [comment]
@elax46 why did you close?

**Comment by cedricboitte** [comment]
@shaiu  Why this issue is closed ? I have exactly the same issue. Thanks for sharing a solution.

**Comment by shaiu** [comment]
@cedricboitte 
can you follow this: https://github.com/shaiu/technicolor/issues/11#issuecomment-1040563144
and share the logs?

**Comment by cedricboitte** [comment]
2022-08-03 17:09:53 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration technicolor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-03 17:10:51 INFO (MainThread) [custom_components.technicolor.device_tracker] add_entities tracked $set()

Model of Technicolor : CGA4233

Hoping it will help you .

**Comment by elax46** [comment]
> @elax46 why did you close?

I closed the request because my device is customized by my ISP so there is only the motherboard in technicolor

**Comment by cedricboitte** [comment]
Complete log :

Logger: homeassistant.config_entries
Source: components/system_log/__init__.py:96
First occurred: 14:52:28 (1 occurrences)
Last logged: 14:52:28

Error setting up entry 192.168.0.1 for technicolor
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/technicolorgateway/__init__.py", line 29, in srp6authenticate
    token = self._br.find(lambda tag: tag.has_attr('name') and tag['name'] == 'CSRFtoken')['content']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/technicolor/router.py", line 42, in setup
    await self.hass.async_add_executor_job(self._api.srp6authenticate)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/technicolorgateway/__init__.py", line 60, in srp6authenticate
    _LOGGER.error("Authentication failed. Exception: ", e)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 179, in emit
    entry = LogEntry(
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 96, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/technicolor/__init__.py", line 46, in async_setup_entry
    await technicolor_router.setup()
  File "/config/custom_components/technicolor/router.py", line 44, in setup
    _LOGGER.exception("Failed to connect to Technicolor", e)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1512, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 179, in emit
    entry = LogEntry(
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 96, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

**Comment by DavidFFerreira** [comment]
Same probleme here, same error "TypeError: not all arguments converted during string formatting"

**Comment by tproulund** [comment]
I am having the same issue that there is no devices being detected

this is from the log using your debug command in the configuration file

`2022-09-24 10:10:44.570 INFO (MainThread) [custom_components.technicolor.router] update_all
2022-09-24 10:10:44.571 INFO (MainThread) [custom_components.technicolor.router] update_device_trackers
2022-09-24 10:10:46.193 INFO (MainThread) [custom_components.technicolor.router] update_device_trackers devices $[]
2022-09-24 10:10:46.206 INFO (MainThread) [custom_components.technicolor.device_tracker] add_entities tracked $set()`

and here is the data structure from the router

![devices](https://user-images.githubusercontent.com/26765583/192088084-a429ec9a-164c-40d6-bfc3-33ca6e12d54d.png)

and the router info
![router](https://user-images.githubusercontent.com/26765583/192088085-2c280c7b-f1eb-4f6c-b9d1-f901721073d0.png)

**Comment by shaiu** [comment]
@tproulund @cedricboitte 
Can you check if issue is fixed in the new version?

**Comment by cedricboitte** [comment]
@shaiu thanks for the up-date . Please find herebelow the issue :
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.technicolor.router
Source: custom_components/technicolor/router.py:42
Integration: Technicolor (documentation, issues)
First occurred: 10:38:18 (1 occurrences)
Last logged: 10:38:18

Bad logger message: Failed to connect to Technicolor ((TypeError("'NoneType' object is not subscriptable"),))
Traceback (most recent call last):
  File "/config/custom_components/technicolor/router.py", line 42, in setup
    await self.hass.async_add_executor_job(self._api.srp6authenticate)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/technicolorgateway/__init__.py", line 29, in srp6authenticate
    token = self._br.find(lambda tag: tag.has_attr('name')
TypeError: 'NoneType' object is not subscriptable

**Comment by shaiu** [comment]
@cedricboitte 
I need the html source of http://192.168.1.1/login.lp
or whatever your login page is

**Comment by cedricboitte** [comment]
@shaiu , hi . please find herebelow. Thanks for your follow-up. 

<html>
<body>




<!DOCTYPE html>
  | <html>
  |  
  | <head>
  | <meta charset="utf-8">
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | 
  | <link type="text/css" rel="stylesheet" href="css/theme/voo/style.css" media="screen,projection" id="style_style" />
  | 
  | <link type="text/css" rel="stylesheet" href="css/theme/voo/app.css" media="screen,projection" id="style_app" />
  | <link type="text/css" rel="stylesheet" href="css/main.css" media="screen,projection" id="style_main" />
  | 
  | 
  | <link type="text/css" rel="stylesheet" href="css/theme/voo/menuleft.css" layout="menuleft" id="style_menu">
  | 
  | <script src="js/ie.fix.js"></script>
  | <script src="js/sjcl.js"></script>
  | 
  | <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  | <meta name="apple-mobile-web-app-capable" content="yes" />
  | <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  | </head>
  |  
  | <body class="mh-100">
  | <style>
  | #main-wrap-header {
  | background-color: #ffffff;
  | height: 70px;
  | line-height: 0;
  | }
  |  
  | #header-logo {
  | top: 30px;
  | height: 30px;
  | width: 73px;
  | position: relative;
  | cursor: pointer;
  | }
  |  
  | #icon-header {
  | top: 15px;
  | right: 15px;
  | }
  |  
  | .language {
  | float: right;
  | position: relative;
  | right: 0;
  | top: 0px;
  | }
  |  
  | .login_link{
  | float: right;
  | position: relative;
  | right: -75%;
  | top: -30px;
  | z-index: 9999;
  | font-weight: bold;
  | }
  |  
  | @media only screen and (max-width: 1180px) {
  | #header-logo {
  | display: inline-block;
  | padding: 10px;
  | top: 0px;
  | }
  | .language {
  | right: 5%;
  | top: 10px;
  | }
  | }
  | @media only screen and (max-width: 600px) {
  | .language {
  | right: 5px;
  | }
  | .header_text {
  | padding: 10px;
  | margin-left: 0px;
  | display: block ;
  | }
  | }
  | </style>
  | <div id="login">
  | </div>
  | <div id="page" class="mh-100">
  | <div class="pushy pushy-left">
  | <ul id="side-menu"></ul>
  | <a href="#/logout" tabindex="-1" class='btn blue mb-40 mt-20 ml-20' data-label="HEADER_LOGOUT" style="font-size: 13px;"></a>
  | </div>
  | <div class="site-overlay"></div>
  | <div id="container" class="mh-100" style="display:none;">
  | <div class="header">
  | <div class="main-wrap h-100" id="main-wrap-header">
  | <div class="menu-btn">
  | <div onclick="" class="icon m voo-bg" original-title="menu"><i class="icon-menu"></i></div>
  | </div>
  |  
  | <div id="header-logo">
  | <img src="image/voo/voo_logo.svg">
  | </div>
  | <div class="language">
  | <select id="language-select">
  | <option value="fr" href="lang/fr.json">Français</option>
  | <option value="nl" href="lang/nl.json">Nederlands</option>
  | <option value="de" href="lang/de.json">Deutsch</option>
  | <option value="en" href="lang/en.json">English</option>
  | </select>
  | <a id="to-basic" href="#/basic" class="header_text" data-label="HEADER_VIEW_MODE" original-title="MSG_CHANGE_VIEW"></a>
  | <a id="to-advance" href="#/status" class="header_text" data-label="HEADER_VIEW_MODE" original-title="MSG_CHANGE_VIEW" style="display:none;"></a>
  | <a id="to-logout" href="#/logout" class="header_text" data-label="HEADER_LOGOUT" original-title="MSG_LOGOUT"></a>
  | </div>
  | <div class="head-wrap">
  | <ul class="header-nav" id="header-menu">
  | </ul>
  | </div>
  | </div>
  | </div>
  | <div class="sub-header">
  | <div class="sub-nav-container main-wrap">
  | <ul class="sub-nav" id="sub-menu">
  | </ul>
  | </div>
  | </div>
  | <div class="main main-wrap h-100" id="main">
  | <ul class="left-nav pt-40 mr-20" id="left-menu"></ul>
  | <div id="main_container" class="mt-40 pb-60"></div>
  | </div>
  | <div class="basic-view">
  | </div>
  | 
  | 
  | </div>
  | <div class="footer">
  | <div class="main-wrap">
  | <small>© <script>document.write( new Date().getFullYear() );</script> Technicolor. All rights reserved. </small>
  | </div>
  | </div>
  |  
  | </div>
  | <div class="help-wrap" style="display:none;">
  | <a id="help-btn" class="animate-arrow" href="javascript:"> HELP &nbsp;</a>
  | <div id="help-container" class="main-wrap"></div>
  | </div>
  | <div class="dev-wrap">
  | <select id="language-select-login" style="border:none;">
  | <option value="fr" href="lang/fr.json">Français</option>
  | <option value="nl" href="lang/nl.json">Nederlands</option>
  | <option value="de" href="lang/de.json">Deutsch</option>
  | <option value="en" href="lang/en.json">English</option>
  | </select>
  | <div class="login_link hidden">
  | <a id="to-login" href="javascript:" class="header_text" data-label="HEADER_LOGIN"></a>
  | </div>
  | </div>
  | <script src="js/jquery-3.3.1.js"></script>
  | <script src="js/jquery.swipe-events.js"></script>
  | <script src="js/jquery.modal.js"></script>
  | <script src="js/jquery.tipsy.js"></script>
  | <script src="js/jquery.validate.js"></script>
  | <script src="js/jquery.siteCheck.js"></script>
  | <script src="js/jquery.dataTables.min.js"></script>
  | <script src="js/path.js"></script>
  | <script src="js/path.helper.js"></script>
  | <script src="js/tmpl.js"></script>
  | <script src="js/pushy.js"></script>
  | <script src="js/preprocesser.js"></script>
  | <script src="js/translator.js"></script>
  | <script src="js/dragula.min.js"></script>
  | <script src="js/nprogress.js"></script>
  | <script src="js/sjcl.js"></script>
  | <script src="js/common_scripts.js"></script>
  | <script src="js/chart-2.7.1.js"></script>
  | <script src="js/utils.js"></script>
  |  
  | 
  | <script>
  | $.getScript("js/app/app.js");
  | </script>
  |  
  | <script type="text/x-tmpl" id="menu-tmpl">
  | {% for(var i in o){ %}
  | <li>
  | <a href="{%=i %}" data-label="{%=o[i].value %}"></a>
  | </li>
  | {% }%}
  | </script>
  | <script type="text/x-tmpl" id="side-menu-tmpl">
  | {% for(var i in o){ %} {% if(o[i].sub){ var sub = o[i].sub; %}
  | <li class="pushy-dropdown">
  | <span tabindex="0" href="{%=i %}" data-label="{%=o[i].value %}"></span>
  | <ul>
  | {% for(var j in sub){ %}
  | <li>
  | <a href="{%=j %}" data-label="{%=sub[j].value %}"></a>
  | </li>
  | {% } %}
  | </ul>
  | </li>
  | {% }else{ %}
  | <li><a href="{%=i %}">{%=o[i].value %}</a></li>
  | {% } %} {% }%}
  | </script>
  | </body>
  |  
  | </html>
 

<br class="Apple-interchange-newline">
</body>
</html><!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <link type="text/css" rel="stylesheet" href="[css/theme/voo/style.css](http://192.168.0.1/css/theme/voo/style.css)" media="screen,projection" id="style_style" />
    
    <link type="text/css" rel="stylesheet" href="[css/theme/voo/app.css](http://192.168.0.1/css/theme/voo/app.css)" media="screen,projection" id="style_app" />
    <link type="text/css" rel="stylesheet" href="[css/main.css](http://192.168.0.1/css/main.css)" media="screen,projection" id="style_main" />
    
    
    <link type="text/css" rel="stylesheet" href="[css/theme/voo/menuleft.css](http://192.168.0.1/css/theme/voo/menuleft.css)" layout="menuleft" id="style_menu">
    
    <script src="[js/ie.fix.js](http://192.168.0.1/js/ie.fix.js)"></script>
    <script src="[js/sjcl.js](http://192.168.0.1/js/sjcl.js)"></script>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
</head>

<body class="mh-100">
    <style>
        #main-wrap-header {
            background-color: #ffffff;
            height: 70px;
            line-height: 0;
        }
        
        #header-logo {
            top: 30px;
            height: 30px;
            width: 73px;
            position: relative;
            cursor: pointer;
        }

        #icon-header {
            top: 15px;
            right: 15px;
        }

        .language {
            float: right;
            position: relative;
            right: 0;
            top: 0px;
        }
        
        .login_link{
            float: right;
            position: relative;
            right: -75%;
            top: -30px;
            z-index: 9999;
            font-weight: bold;
        }

        @media only screen and (max-width: 1180px) {
            #header-logo {
                display: inline-block;
                padding: 10px;
                top: 0px;
            }
            .language {
                right: 5%;
                top: 10px;
            }
        }
        @media only screen and (max-width: 600px) {
            .language {
                right: 5px;
            }
            .header_text {
                padding: 10px;
                margin-left: 0px;
                display: block ;
            }
        }
    </style>
    <div id="login">
    </div>
    <div id="page" class="mh-100">
        <div class="pushy pushy-left">
            <ul id="side-menu"></ul>
            <a href="[#/logout](http://192.168.0.1/#/logout)" tabindex="-1" class='btn blue mb-40 mt-20 ml-20' data-label="HEADER_LOGOUT" style="font-size: 13px;"></a>
        </div>
        <div class="site-overlay"></div>
        <div id="container" class="mh-100" style="display:none;">
            <div class="header">
                <div class="main-wrap h-100" id="main-wrap-header">
                    <div class="menu-btn">
                        <div onclick="" class="icon m voo-bg" original-title="menu"><i class="icon-menu"></i></div>
                    </div>

                    <div id="header-logo">
                            <img src="[image/voo/voo_logo.svg](http://192.168.0.1/image/voo/voo_logo.svg)">
                    </div>
                    <div class="language">
                        <select id="language-select">
                            <option value="fr" href="[lang/fr.json](http://192.168.0.1/lang/fr.json)">Français</option>
                            <option value="nl" href="[lang/nl.json](http://192.168.0.1/lang/nl.json)">Nederlands</option>
                            <option value="de" href="[lang/de.json](http://192.168.0.1/lang/de.json)">Deutsch</option>
                            <option value="en" href="[lang/en.json](http://192.168.0.1/lang/en.json)">English</option>
                        </select>
                        <a id="to-basic" href="[#/basic](http://192.168.0.1/#/basic)" class="header_text" data-label="HEADER_VIEW_MODE" original-title="MSG_CHANGE_VIEW"></a>
                        <a id="to-advance" href="[#/status](http://192.168.0.1/#/status)" class="header_text" data-label="HEADER_VIEW_MODE" original-title="MSG_CHANGE_VIEW" style="display:none;"></a>
                        <a id="to-logout" href="[#/logout](http://192.168.0.1/#/logout)" class="header_text" data-label="HEADER_LOGOUT" original-title="MSG_LOGOUT"></a>
                    </div>
                    <div class="head-wrap">
                        <ul class="header-nav" id="header-menu">
                        </ul>
                    </div>
                </div>
            </div>
            <div class="sub-header">
                <div class="sub-nav-container main-wrap">
                    <ul class="sub-nav" id="sub-menu">
                    </ul>
                </div>
            </div>
            <div class="main main-wrap h-100" id="main">
                <ul class="left-nav pt-40 mr-20" id="left-menu"></ul>
                <div id="main_container" class="mt-40 pb-60"></div>
            </div>
            <div class="basic-view">
            </div>
            
            
        </div>
        <div class="footer">
            <div class="main-wrap">
                <small>© <script>document.write( new Date().getFullYear() );</script> Technicolor. All rights reserved. </small>
            </div>
        </div>

    </div>
    <div class="help-wrap" style="display:none;">
        <a id="help-btn" class="animate-arrow" href="[javascript:](about:blank)"> HELP &nbsp;</a>
        <div id="help-container" class="main-wrap"></div>
    </div>
    <div class="dev-wrap">
        <select id="language-select-login" style="border:none;">
            <option value="fr" href="[lang/fr.json](http://192.168.0.1/lang/fr.json)">Français</option>
            <option value="nl" href="[lang/nl.json](http://192.168.0.1/lang/nl.json)">Nederlands</option>
            <option value="de" href="[lang/de.json](http://192.168.0.1/lang/de.json)">Deutsch</option>
            <option value="en" href="[lang/en.json](http://192.168.0.1/lang/en.json)">English</option>
        </select>
        <div class="login_link hidden">
            <a id="to-login" href="[javascript:](about:blank)" class="header_text" data-label="HEADER_LOGIN"></a>
        </div>
    </div>
    <script src="[js/jquery-3.3.1.js](http://192.168.0.1/js/jquery-3.3.1.js)"></script>
    <script src="[js/jquery.swipe-events.js](http://192.168.0.1/js/jquery.swipe-events.js)"></script>
    <script src="[js/jquery.modal.js](http://192.168.0.1/js/jquery.modal.js)"></script>
    <script src="[js/jquery.tipsy.js](http://192.168.0.1/js/jquery.tipsy.js)"></script>
    <script src="[js/jquery.validate.js](http://192.168.0.1/js/jquery.validate.js)"></script>
    <script src="[js/jquery.siteCheck.js](http://192.168.0.1/js/jquery.siteCheck.js)"></script>
    <script src="[js/jquery.dataTables.min.js](http://192.168.0.1/js/jquery.dataTables.min.js)"></script>
    <script src="[js/path.js](http://192.168.0.1/js/path.js)"></script>
    <script src="[js/path.helper.js](http://192.168.0.1/js/path.helper.js)"></script>
    <script src="[js/tmpl.js](http://192.168.0.1/js/tmpl.js)"></script>
    <script src="[js/pushy.js](http://192.168.0.1/js/pushy.js)"></script>
    <script src="[js/preprocesser.js](http://192.168.0.1/js/preprocesser.js)"></script>
    <script src="[js/translator.js](http://192.168.0.1/js/translator.js)"></script>
    <script src="[js/dragula.min.js](http://192.168.0.1/js/dragula.min.js)"></script>
    <script src="[js/nprogress.js](http://192.168.0.1/js/nprogress.js)"></script>
    <script src="[js/sjcl.js](http://192.168.0.1/js/sjcl.js)"></script>
    <script src="[js/common_scripts.js](http://192.168.0.1/js/common_scripts.js)"></script>
    <script src="[js/chart-2.7.1.js](http://192.168.0.1/js/chart-2.7.1.js)"></script>
    <script src="[js/utils.js](http://192.168.0.1/js/utils.js)"></script>

    
    <script>
        $.getScript("js/app/app.js");
    </script>

    <script type="text/x-tmpl" id="menu-tmpl">
        {% for(var i in o){ %}
        <li>
            <a href="{%=i %}" data-label="{%=o[i].value %}"></a>
        </li>
        {% }%}
    </script>
    <script type="text/x-tmpl" id="side-menu-tmpl">
        {% for(var i in o){ %} {% if(o[i].sub){ var sub = o[i].sub; %}
        <li class="pushy-dropdown">
            <span tabindex="0" href="{%=i %}" data-label="{%=o[i].value %}"></span>
            <ul>
                {% for(var j in sub){ %}
                <li>
                    <a href="{%=j %}" data-label="{%=sub[j].value %}"></a>
                </li>
                {% } %}
            </ul>
        </li>
        {% }else{ %}
        <li><a href="{%=i %}">{%=o[i].value %}</a></li>
        {% } %} {% }%}
    </script>
</body>

</html>

**Comment by shaiu** [comment]
@cedricboitte thanks but this doesn't look like the html I need.
I need the page that holds the username/password login page.
The html code should have a `form` element in it.

**Comment by cedricboitte** [comment]
you mean this page ...
![image](https://user-images.githubusercontent.com/65857268/216942298-64e9cb9e-7967-4ef8-913f-15f4ac6ede8c.png)

Explain me exactly what you want .. I shared in my previous post the html code of this one .. so I don't really understand.

**Comment by shaiu** [comment]
Yes!

**Comment by cedricboitte** [comment]
[page.txt](https://github.com/shaiu/technicolor/files/10661855/page.txt)

**Comment by Zi0mele** [comment]
I have the same issue. These are the details of my router:

Nome fornitore: Technicolor
Nome prodotto: MediaAccess FGA2130FWB
Versione software: 1.0.1b
Versione firmware: 18.3.n.0482_FW_233_FGA2130
Versione hardware: GBNT-2

I tried the debug, and this is the only log i could find related to the integration: 

- Logger: technicolorgateway
Source: /usr/local/lib/python3.10/site-packages/technicolorgateway/__init__.py:63 
First occurred: 09:57:45 (1 occurrences) 
Last logged: 09:57:45

Authentication failed. Exception: 'NoneType' object is not subscriptable

- Logger: custom_components.technicolor.router
Source: custom_components/technicolor/router.py:42 
Integration: Technicolor ([documentation](https://github.com/shaiu/technicolor), [issues](https://github.com/shaiu/technicolor/issues)) 
First occurred: 09:57:46 (1 occurrences) 
Last logged: 09:57:46

Bad logger message: Failed to connect to Technicolor ((TypeError("'NoneType' object is not subscriptable"),))
Traceback (most recent call last):
  File "/config/custom_components/technicolor/router.py", line 42, in setup
    await self.hass.async_add_executor_job(self._api.srp6authenticate)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/technicolorgateway/__init__.py", line 31, in srp6authenticate
    token = token_tag['content']
TypeError: 'NoneType' object is not subscriptable

Could the Fastweb (my ISP) customization ve the issue? I tried to get the modals as you asked in previous comments, but i couldn't. Another issue with the customization, i guess.

Thanks

**Comment by shaiu** [comment]
@Zi0mele @cedricboitte 
I've released a new version 0.3.0
Can you check if it fixes the issue?
Thanks

**Comment by Zi0mele** [comment]
Hi,
thanks for your answer and for the update.
I tried updating the integration, restarted HA and even deleted and reinstalled the integration, just to be sure. Still same errors:

- Logger: custom_components.technicolor.router
Source: custom_components/technicolor/router.py:42 
Integration: Technicolor ([documentation](https://github.com/shaiu/technicolor), [issues](https://github.com/shaiu/technicolor/issues)) 
First occurred: 09:25:44 (3 occurrences) 
Last logged: 11:22:44

Bad logger message: Failed to connect to Technicolor ((TypeError("'NoneType' object is not subscriptable"),))
Traceback (most recent call last):
  File "/config/custom_components/technicolor/router.py", line 42, in setup
    await self.hass.async_add_executor_job(self._api.authenticate)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/technicolorgateway/__init__.py", line 67, in authenticate
    return self.srp6authenticate()
  File "/usr/local/lib/python3.10/site-packages/technicolorgateway/__init__.py", line 30, in srp6authenticate
    token = token_tag['content']
TypeError: 'NoneType' object is not subscriptable

- Logger: technicolorgateway
Source: /usr/local/lib/python3.10/site-packages/technicolorgateway/__init__.py:71 
First occurred: 09:25:44 (3 occurrences) 
Last logged: 11:22:44

Authentication failed. Exception: 'NoneType' object is not subscriptable

**Comment by shaiu** [comment]
@Zi0mele 
can you please follow this:

https://github.com/shaiu/technicolor/issues/11#issuecomment-1040563144

and then post the debug logs?

**Comment by Cr4z33** [comment]
> can you please add this to your configuration.yaml:
> 
> ```
> logger:
>   default: warning
>   logs:
>     custom_components.technicolor: debug
> ```
> 
>     1. then remove the custom component
> 
>     2. restart HA
> 
>     3. add the component again
> 
> 
> Look at the logs and please attach relevant logs here (mask your ips if there are)

@shaiu I've got the same issue with a DGA4331, but I cannot find the wanted log.

What is please the path to it in HA?

**Comment by elax46** [comment]
> > @elax46
> > can you please add this to your configuration.yaml:
> > ```
> > logger:
> >   default: warning
> >   logs:
> >     custom_components.technicolor: debug
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 1. then remove the custom component
> > 
> > 2. restart HA
> > 
> > 3. add the component again
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Look at the logs and please attach relevant logs here (mask your ips if there are)
> 
> I've got the same issue with a DGA4331, but I cannot find the wanted log.
> 
> What is please the path to it in HA?

I'm sorry I can't help you my ISP changed my modem/router so I haven't tried to configure this integration again

**Comment by Cr4z33** [comment]
> > > @elax46
> > > can you please add this to your configuration.yaml:
> > > ```
> > > logger:
> > >   default: warning
> > >   logs:
> > >     custom_components.technicolor: debug
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > 1. then remove the custom component
> > > 
> > > 2. restart HA
> > > 
> > > 3. add the component again
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Look at the logs and please attach relevant logs here (mask your ips if there are)
> > 
> > 
> > I've got the same issue with a DGA4331, but I cannot find the wanted log.
> > What is please the path to it in HA?
> 
> I'm sorry I can't help you my ISP changed my modem/router so I haven't tried to configure this integration again

Sorry I quoted your nickname by mistake! 🤦🏼

**Comment by shaiu** [comment]
> > can you please add this to your configuration.yaml:
> > ```
> > logger:
> >   default: warning
> >   logs:
> >     custom_components.technicolor: debug
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 1. then remove the custom component
> > 
> > 2. restart HA
> > 
> > 3. add the component again
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Look at the logs and please attach relevant logs here (mask your ips if there are)
> 
> @shaiu I've got the same issue with a DGA4331, but I cannot find the wanted log.
> 
> What is please the path to it in HA?

@Cr4z33 
Did you update the integration to v0.3.0?
Did you add the config in configuration.yaml?

**Comment by Cr4z33** [comment]
> @Cr4z33 Did you update the integration to v0.3.0? Did you add the config in configuration.yaml?
@shaiu yes I did all of the above, but my question was **_where_** can I find then the log in HA? :D

**Comment by shaiu** [comment]
@Cr4z33 

Settings -> System -> Logs

**Comment by Zi0mele** [comment]
> @Zi0mele can you please follow this:
> 
> [#11 (comment)](https://github.com/shaiu/technicolor/issues/11#issuecomment-1040563144)
> 
> and then post the debug logs?

Tried it and went to check the logs in the config folder, but I fond the same logs I've posted earlier.

**Comment by Cr4z33** [comment]
> @Cr4z33
> 
> Settings -> System -> Logs

@shaiu hmmm no error logs for your module... that's strange... 🤔

**Comment by shaiu** [comment]
Check for any log of mine. INFO/DEBUG

**Comment by Cr4z33** [comment]
> Check for any log of mine. INFO/DEBUG

@shaiu please bare with me, but I am still not so used to where to look at in HA. 😅

What's the path to get to your integration's logs please?

**Comment by shaiu** [comment]
@Cr4z33 no worries

You can download the whole log from here:

![Screenshot 2023-04-17 at 13 37 50](https://user-images.githubusercontent.com/1286993/232461847-a92ccadb-c574-406d-9b06-cbadb3959dee.png)

then just look for logs with the topic 'custom_components.technicolor'

**Comment by Cr4z33** [comment]
@shaiu thanks, [here](https://pastebin.com/0BKjBpTu)'s the log.

**Comment by shaiu** [comment]
@Cr4z33 

Please also add under logs (in configurration.yaml):

`technicolorgateway: debug`

so the final configuration will be:

```
logs:
    custom_components.technicolor: debug
    technicolorgateway: debug
```

then please uninstall the integration and install it again (so we will have a fresh install with all logs)

Thanks

**Comment by Cr4z33** [comment]
@shaiu OK so here's the new log according to your request:

https://pastebin.com/LXzJqahH

**Comment by shaiu** [comment]
@Cr4z33 great. 
Now we are getting somewhere.

I need the following:

1. go to the page where you see all the addresses
2. I need the html file of that page
3. also I need the url of that page

That will let me know why no devices are getting back to the integration

Thanks

**Comment by Cr4z33** [comment]
@shaiu  [Here](https://pastebin.com/Fnu69zgU) is the HTML and the URL of that page is [http://routeripaddress/modals/device-modal.lp](http://routeripaddress/modals/device-modal.lp).

**Comment by shaiu** [comment]
@Cr4z33 weird.. it was supposed to work. I've tried with the html you gave me and it passed my tests.
I've released version 0.4.0 that contains more debug logs.
Can you update and try again to remove the integration and add it back?
Then paste the logs again.

Thanks!

**Comment by Cr4z33** [comment]
Still not populating.

[Here](https://pastebin.com/t87jTtSC)'s the new log, but tell me... is it supposed to contain all that router HTML code in it? 🤔

**Comment by shaiu** [comment]
@Cr4z33 
Yes. I intentionally print so much to understand the problem.
You can remove the rows in configuration.yaml and restart HA - that will stop the printing.

**Comment by Cr4z33** [comment]
@shaiu alright I'll leave the debugging part in the config until the issue is gone. 😄

**Comment by shaiu** [comment]
@Cr4z33 I've released a new version 0.5.0
Can you please try it?
Thanks

**Comment by Cr4z33** [comment]
@shaiu bingo it's finally working and populating with entities! 

https://imgur.com/a/X33PeO1

Thanks for all your support and efforts!

**Comment by shaiu** [comment]
@Cr4z33 glad to hear that!

Thanks for all your corporation!

**Comment by DrSpaldo** [comment]
Mine isn't working either. Not sure if you want a new issue or if I just post on this one?

Here is the HTML from https://192.168.0.1/modals/device-modal.lp

[device-modal.lp.txt](https://github.com/shaiu/technicolor/files/11581448/device-modal.lp.txt)

Here are the HA logs:

```
Home Assistant Core
2023-05-27 19:45:22.891 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Running pre installation steps
2023-05-27 19:45:22.891 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Pre installation steps completed
2023-05-27 19:45:22.891 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Running installation steps
2023-05-27 19:45:25.824 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Download of router.py completed
2023-05-27 19:45:25.828 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Download of const.py completed
2023-05-27 19:45:25.833 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Download of manifest.json completed
2023-05-27 19:45:25.834 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Download of __init__.py completed
2023-05-27 19:45:25.838 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Download of device_tracker.py completed
2023-05-27 19:45:25.839 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Download of config_flow.py completed
2023-05-27 19:45:25.841 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Download of strings.json completed
2023-05-27 19:45:25.853 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Download of en.json completed
2023-05-27 19:45:26.855 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Installation steps completed
2023-05-27 19:45:26.855 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Running post installation steps
2023-05-27 19:45:26.892 INFO (SyncWorker_6) [homeassistant.loader] Loaded technicolor from custom_components.technicolor
2023-05-27 19:45:26.892 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration technicolor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-27 19:45:26.904 INFO (MainThread) [custom_components.hacs] <Integration shaiu/technicolor> Post installation steps completed
2023-05-27 19:46:05.658 INFO (MainThread) [homeassistant.setup] Setting up technicolor
2023-05-27 19:46:05.658 INFO (MainThread) [homeassistant.setup] Setup of domain technicolor took 0.0 seconds
2023-05-27 19:46:05.666 INFO (SyncWorker_2) [technicolorgateway] trying srp6authenticate
2023-05-27 19:46:06.469 INFO (SyncWorker_2) [technicolorgateway] srp6authenticate success
2023-05-27 19:46:06.469 INFO (MainThread) [custom_components.technicolor.router] update_all
2023-05-27 19:46:06.469 INFO (MainThread) [custom_components.technicolor.router] update_device_trackers
2023-05-27 19:46:06.692 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.0.1 for technicolor
File "/config/custom_components/technicolor/__init__.py", line 46, in async_setup_entry
await technicolor_router.setup()
File "/config/custom_components/technicolor/router.py", line 47, in setup
File "/config/custom_components/technicolor/router.py", line 56, in update_all
File "/config/custom_components/technicolor/router.py", line 61, in update_device_trackers
File "/usr/local/lib/python3.10/site-packages/technicolorgateway/__init__.py", line 80, in get_device_modal
File "/usr/local/lib/python3.10/site-packages/technicolorgateway/__init__.py", line 94, in get_device_modals
File "/usr/local/lib/python3.10/site-packages/technicolorgateway/modal.py", line 40, in get_device_modal
File "/usr/local/lib/python3.10/site-packages/technicolorgateway/modal.py", line 63, in get_data_from_rows
```

**Comment by shaiu** [comment]
@DrSpaldo thanks for reporting.
looks like the modal.lp you provided doesn't have a list/table of ip addresses.
Can you check again?

**Comment by DrSpaldo** [comment]
> looks like the modal.lp you provided doesn't have a list/table of ip addresses. Can you check again?

Thanks for the reply @shaiu. Sorry, I didn't realise I had to login first, see logged in version attached:
[device-modal.lp.txt](https://github.com/shaiu/technicolor/files/11583904/device-modal.lp.txt)

**Comment by shaiu** [comment]
@DrSpaldo I've released a fix. version v0.6.0
Please check in home assistant and update

**Comment by DrSpaldo** [comment]
> @DrSpaldo I've released a fix. version v0.6.0 Please check in home assistant and update

Thanks for the quick response and update @shaiu . The integration/device now loads!  

I am not sure exactly if it is doing the correct thing or not though. At the moment, I am only getting a device tracker (my router) and nothing else. Should it be displaying any information about the router/modem itself? For example, speeds in & out, etc

**Comment by shaiu** [comment]
@DrSpaldo  It's only a device tracker

**Comment by DrSpaldo** [comment]
Ok, thanks
